### ISSUE TITLE
Waiting too much for all error replies

### ISSUE THREAD

**Issue by denizea** [fido-alliance/jovasco-u2f-ref-code#2]
Hi, 
I was reviewing the BLE Testing Tool Source Code and realized a delay for 2000 ms in u2f-ref-code/u2f-tests/BLE/BLETest/BLETransportTests.cpp:227 that helps Testing Tool to collect all Error Replies (Error Messages starts with 0xBF). 

However, waiting 2000 ms creates a race conditions kErrorWaitMillis (which is 2000 ms, please see U2F BLE 1.1 Spec for kErrorWaitMillis). We believe that 2000ms is way to long to collect error messages. 

If we would like to wait to collect error messages, 1000 ms is more than enough in my opinion.

What do you think about this?

Thank you,

**Comment by jovasco** [comment]
I have no issue with this change.

**Comment by jovasco** [comment]
I have changed this to 1500ms, I remember increasing this after some issues. 500ms should be plenty of buffer.

Released version 1.1.1
