### ISSUE TITLE
Cannot build imported project on Visual Studio 2017/2015

### ISSUE THREAD

**Issue by Coconop** [fido-alliance/jovasco-u2f-ref-code#8]
I have Windows 10 and Visual Studio Community 2017.
I installed the default environment for Desktop  C/C++ application and among other modules:

- VC++ 2015.3 v14 toolset for desktop
- Windows Universal CRT SDK

 When I try to build the projet I get:
`Error	C1107	could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable`

I then installed Visual Studio 2015, still got same error but on other file: _Windows.winmd_

I found some pointers on these issue but it requires to change some parameters in Project Properties > C/C++ but I don't have this section available (the project seems not to be identified as a C++ project, in _ProjectDefaults_ I have the field _.NET Target Framework Version_).

I found the required files (for example platform.winmd) in Visual Studio folder but cannot acces the corresponding parameter to set in properties.

**Comment by jovasco** [comment]
You need to fix this line in Makefile.win:

> CFLAGS_WINRT = -ZW -Gm- -AI"C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/vcpackages" -AI"C:/Program Files (x86)/Windows Kits/10/References/"  -AI"C:/Program Files (x86)/Windows Kits/10/UnionMetaData/"


You need to add the correct Windows Kit version, for example:

> -AI"C:/Program Files (x86)/Windows Kits/10/References/10.0.17763.0/"  -AI"C:/Program Files (x86)/Windows Kits/10/UnionMetaData/10.0.17763.0/"

I haven't found a way to determine this path automatically.

Please note that this tool is deprecated.

**Comment by Coconop** [comment]
That was the fix indeed, build is ok now :)
Thanks
